//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehouseWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public Nullable<int> ownerId { get; set; }
        public string CurrentState { get; set; }
        public string Condition { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public Nullable<bool> ForRent { get; set; }
        public Nullable<bool> ForBorrow { get; set; }
        public string Description { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<int> RentPrice { get; set; }
    }
}
