//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehouseWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string Type { get; set; }
        public string Business { get; set; }
        public string Customer { get; set; }
        public string State { get; set; }
        public string Date { get; set; }
        public string RequesterNotes { get; set; }
        public string RequesteeNotes { get; set; }
        public string AdminNotes { get; set; }
    }
}
